### ISSUE TITLE
Command: git remote set-url gives me problems as documented?

### ISSUE THREAD

**Issue by michaelbowler** [github/docs#2831]
Command: `git remote set-url` gives me problems as documented, see https://docs.github.com/en/free-pro-team@latest/github/using-git/changing-a-remotes-url

1. Run `git remote set-url origin git@github.com:USERNAME/REPOSITORY.git` on my repo
2.  Run `git pull`
3.  I get an error like:
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
4.  Instead run `git remote set-url origin git@github.com:/REPOSITORY.git` (minus the username)
5. Run `git pull` - no error and the repo pulls

Do you need to correct the documentation for the command?

Or am I missing something?

**Comment by chiedo** [comment]
Thanks @michaelbowler! Someone will take a look.

**Comment by jsoref** [comment]
@michaelbowler: you don't have ssh configured for github -- see https://github.com/michaelbowler.keys

These pages are what you need:
https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh
https://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

If I don't have a `~/.ssh/` directory configured, this is what I see:
```sh
% git ls-remote git@github.com:github/docs.git
The authenticity of host 'github.com (140.82.113.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

When I have `~/.ssh/config` + `~/.ssh/id_rsa` and https://github.com/jsoref.keys, the above command works properly. And I can run:
```sh
% ssh github.com
Hi jsoref! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by janiceilene** [comment]
Thanks so much @jsoref! Looks like this is resolved, let us know if you see any documentation update needs!

**Comment by michaelbowler** [comment]
Hi Josh, Thanks for he update, but I'm still struggling with this.My enterprise account (michaelb not michaelbowler) is configured for github.so, https://github.com/michaelb.keys works and I can see my ssh key...I also have a ~/.ssh/ directory and can see my id_rsa and id_rsa.pub just fine.I have re-added said rsa key to my github, see: But when I run % ssh github.com, I getAzureAD+MICHAELBOWLER@LAPTOP-DSJBBHS9 MINGW64 ~ (master)$ ssh github.comAzureAD+MICHAELBOWLER@github.com: Permission denied (publickey).I think there is some internal mismatch in github between "michaelb" and "MICHAELBOWLER" - what do you think?RgdsMICHAEL BOWLERInformation designerPhone: 353-1-815-2130E-mail: michaelb@ie.ibm.com-----Josh Soref <notifications@github.com> wrote: -----To: github/docs <docs@noreply.github.com>From: Josh Soref <notifications@github.com>Date: 02/18/2021 05:16AMCc: Michael Bowler <michaelb@ie.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [github/docs] Command: git remote set-url gives me problems as documented? (#2831)@michaelbowler: you don't have ssh configured for github -- see https://github.com/michaelbowler.keysThese pages are what you need:https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-sshhttps://docs.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-accountIf I don't have a ~/.ssh/ directory configured, this is what I see:% git ls-remote git@github.com:github/docs.gitThe authenticity of host 'github.com (140.82.113.4)' can't be established.RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.Are you sure you want to continue connecting (yes/no/[fingerprint])? yesWarning: Permanently added 'github.com,140.82.113.4' (RSA) to the list of known hosts.git@github.com: Permission denied (publickey).fatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.When I have ~/.ssh/config + ~/.ssh/id_rsa and https://github.com/jsoref.keys, the above command works properly. And I can run:% ssh github.comHi jsoref! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by jsoref** [comment]
you need to set your thing to ssh as `git` not your username.

```
ssh git@github.com
```
should work.

And thus, you should be able to do a git clone via ssh.

fwiw, I have this in `~/.ssh/config`:
```
host github.com
RequestTTY no
user git
```
Which lets me `ssh github.com` instead of having to type `ssh git@github.com`.

**Comment by michaelbowler** [comment]
Thanks Josh,I still get $ ssh git@github.comgit@github.com: Permission denied (publickey).I already have a config file containing:Host github.ibm.comUser michaelb@github.ibm.comIdentityFile ~/.ssh/id_rsaThink changing 2nd line to user gitmight help...MICHAEL BOWLERInformation designerPhone: 353-1-815-2130E-mail: michaelb@ie.ibm.com-----Josh Soref <notifications@github.com> wrote: -----To: github/docs <docs@noreply.github.com>From: Josh Soref <notifications@github.com>Date: 03/01/2021 09:57AMCc: Michael Bowler <michaelb@ie.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [github/docs] Command: git remote set-url gives me problems as documented? (#2831)




you need to set your thing to ssh as git not your username.ssh git@github.comshould work.And thus, you should be able to do a git clone via ssh.fwiw, I have this in ~/.ssh/config:host github.comRequestTTY nouser gitWhich lets me ssh github.com instead of having to type ssh git@github.com.

**Comment by ratsspinstar** [comment]
pon., 1 mar 2021 o 02:15 Michael Bowler <notifications@github.com>
napisał(a):
